[tool.ruff]
line-length = 79
target-version = "py311"
fix = true
extend-select = ["I"]  # Enables import sorting

[tool.ruff.format]
quote-style = "single"
docstring-code-format = true
indent-style = "space"