name: Lint and Test

on: [push, pull_request]

# Define the ROS version as a variable for the whole workflow
env:
  ROS_DISTRO: kilted

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Setup ROS using the variable
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          # Use the correct input name and the variable
          required-ros-distributions: ${{ env.ROS_DISTRO }}

      # 3. Cache the pip venv directory
      - name: Cache pip venv
        id: cache-pip
        uses: actions/cache@v4
        with:
          path: venv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install dependencies
      - name: Install dependencies
        run: |
          # Source ROS using the variable
          source /opt/ros/${{ env.ROS_DISTRO }}/setup.bash

          sudo rosdep init || true
          rosdep update

          # Use rosdep to install ROS dependencies
          rosdep install --from-paths src --ignore-src -r -y

          # Install Python-specific packages
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Run lint checks
      - name: Run lint and format checks with Ruff
        run: |
          # Source both environments using the variable
          source /opt/ros/${{ env.ROS_DISTRO }}/setup.bash
          source venv/bin/activate
          ruff check src --fix

      # Run tests
      - name: Run tests
        run: |
          # Source both environments using the variable
          source /opt/ros/${{ env.ROS_DISTRO }}/setup.bash
          source venv/bin/activate
          pytest
