name: Lint and Test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 2. Setup ROS and install dependencies
      - name: Install ROS and dependencies
        run: |
          # Install ROS 2 (using "kilted" as an example)
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y universe
          sudo apt-get update
          sudo apt-get install -y curl
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y ros-kilted-ros-base python3-rosdep python3-colcon-common-extensions

          # Initialize rosdep
          sudo rosdep init
          rosdep update

          # Use rosdep to install dependencies from your package.xml (this will install ackermann-msgs)
          # We use "src" as the directory to search for package.xml files
          rosdep install --from-paths src --ignore-src -r -y

          # Source the ROS environment
          source /opt/ros/kilted/setup.bash

          # Now, install your Python-specific packages
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run lint and format checks with Ruff
        run: |
          # Source both environments: ROS first, then your venv
          source /opt/ros/kilted/setup.bash
          source venv/bin/activate
          ruff check src --fix

      - name: Run tests
        run: |
          # Source both environments: ROS first, then your venv
          source /opt/ros/kilted/setup.bash
          source venv/bin/activate
          pytest
